### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by ghost** [ariejan/slick2d#1]
Hi, could you please specify license of your project? Preferably ISC license if possible. Just adding file called "LICENSE" or "COPYING" into the root of your project with content of your licence would be sufficient.

For your convenience, here is full ISC license:

> Copyright (c) Year(s), Company or Person's Name <E-mail address>
> 
> Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.
> 
> THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Thank you!

**Comment by ariejan** [comment]
This is a fork of https://bitbucket.org/kevglass/slick It's not my place to add a LICENSE to it.
